### ISSUE TITLE
Conflicting packages "i3-gaps-next-git" and "i3-wm"

### ISSUE THREAD

**Issue by brasilikum** [erikdubois/i3wmarchdark#2]
Running 'installation/050-install-i3wm-core-v1.sh' I get this error, resulting in an error unresolvable package conflicts. Any idea what went wrong? 

Thanks for maintaining this repo, it really gets me off the ground!

**Comment by brasilikum** [comment]
Ok, the reason is I previously had installed i3. I understood the problem by watching your video on YouTube.

**Comment by erikdubois** [comment]
best issue ever
solved on its own
;-)
